### ISSUE TITLE
CRAN / pip

### ISSUE THREAD

**Issue by Dasonk** [GjjvdBurg/SyncRNG#1]
This package would be a lot more convenient if it was available via CRAN and pip.  I haven't made anything available via pip so I don't know how hard that process is but it's not too bad to get it on CRAN.  Have you considered this?

**Comment by GjjvdBurg** [comment]
Thanks for checking out this library, I hadn't really put any thought into creating proper packages, but I'll look into it!

**Comment by GjjvdBurg** [comment]
The package is now available through pip and CRAN.
